/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PackDiseño;

import Clases.Placeholders;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.UIManager;

/**
 *
 * @author apnil
 */
public class PanelRegistrarPaciente extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrarPaciente
     */
    private Color col;
    public PanelRegistrarPaciente(Color col) {
        initComponents();
        inicializarPlaceholders();
        lblFecha.setText(EstablecerFecha());
        this.col = col;
        cbGenero.setSelectedIndex(-1);
        EstablecerColor();
        
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch(Exception ex ) {
          System.err.println( "Failed to initialize LaF" );
        }
        
        btnRegistrar.putClientProperty(FlatClientProperties.STYLE, "arc: 20");
        
    }
    private String EstablecerFecha(){
        LocalDate fecha = LocalDate.now();
        int dia = fecha.getDayOfMonth();
        int mesint = fecha.getMonthValue();
        int año = fecha.getYear();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        return "Hoy es " + dia + " del " + meses[mesint-1] + " de " + año;
    }
    private void EstablecerColor(){
        jSeparator1.setForeground(col);
        jSeparator10.setForeground(col);
        jSeparator3.setForeground(col);
        jSeparator4.setForeground(col);
        jSeparator5.setForeground(col);
        jSeparator6.setForeground(col);
        jSeparator7.setForeground(col);
        jSeparator8.setForeground(col);
        jSeparator9.setForeground(col);
        btnRegistrar.setBackground(col);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        dpFechaNac = new org.jdesktop.swingx.JXDatePicker();
        txtDocIdentidad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtAPaterno = new javax.swing.JTextField();
        txtAMaterno = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(970, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setText("Registar nuevo Paciente");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblFecha.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(51, 51, 51));
        lblFecha.setText("Hoy es 0 de Mes de 0000");
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 516, 740, 70));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 10, 410));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombres");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Apellido Paterno");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Documento de Identidad");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 190, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Fecha Nacimiento");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 130, 30));

        txtEdad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEdad.setText("00");
        txtEdad.setEnabled(false);
        add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Edad");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 80, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Genero");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 80, 30));

        cbGenero.setBackground(new java.awt.Color(242, 242, 242));
        cbGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        cbGenero.setOpaque(true);
        add(cbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 50, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 160, 10));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Apellido Materno");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 130, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 160, 10));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Telefono");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 130, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Correo");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 130, 30));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 350, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 350, 10));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Direccion");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 130, 30));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 350, 10));

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 350, 50));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 350, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 350, 10));
        add(dpFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 130, 30));

        txtDocIdentidad.setBackground(new java.awt.Color(242, 242, 242));
        txtDocIdentidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDocIdentidad.setForeground(new java.awt.Color(153, 153, 153));
        txtDocIdentidad.setText("Ingrese el numero de su documento de indentidad (DNI / CE)");
        txtDocIdentidad.setBorder(null);
        add(txtDocIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 350, 30));

        txtDireccion.setBackground(new java.awt.Color(242, 242, 242));
        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(153, 153, 153));
        txtDireccion.setText("Ingrese su Direccion");
        txtDireccion.setBorder(null);
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 350, 30));

        txtAPaterno.setBackground(new java.awt.Color(242, 242, 242));
        txtAPaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAPaterno.setForeground(new java.awt.Color(153, 153, 153));
        txtAPaterno.setText("Ingrese su Apellido Paterno");
        txtAPaterno.setBorder(null);
        add(txtAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 30));

        txtAMaterno.setBackground(new java.awt.Color(242, 242, 242));
        txtAMaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAMaterno.setForeground(new java.awt.Color(153, 153, 153));
        txtAMaterno.setText("Ingrese su Apellido Materno");
        txtAMaterno.setBorder(null);
        add(txtAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 160, 30));

        txtNombres.setBackground(new java.awt.Color(242, 242, 242));
        txtNombres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(153, 153, 153));
        txtNombres.setText("Ingrese sus nombres");
        txtNombres.setBorder(null);
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 350, 30));

        txtTelefono.setBackground(new java.awt.Color(242, 242, 242));
        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefono.setText("Ingrese su Numero de Telefono");
        txtTelefono.setBorder(null);
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 350, 30));

        txtCorreo.setBackground(new java.awt.Color(242, 242, 242));
        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("Ingrese su Correo");
        txtCorreo.setBorder(null);
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 350, 30));
    }// </editor-fold>//GEN-END:initComponents
    public void inicializarPlaceholders(){
        Placeholders.configurarPlaceholder(txtNombres, "Ingrese sus nombres");
        Placeholders.configurarPlaceholder(txtAPaterno, "Ingrese su Apellido Paterno");
        Placeholders.configurarPlaceholder(txtAMaterno, "Ingrese su Apellido Materno");
        Placeholders.configurarPlaceholder(txtTelefono, "Ingrese su Numero de Telefono");
        Placeholders.configurarPlaceholder(txtCorreo, "Ingrese su Correo");
        Placeholders.configurarPlaceholder(txtDireccion, "Ingrese su Direccion");
        Placeholders.configurarPlaceholder(txtDocIdentidad, "Ingrese el numero de su documento de identidad (DNI / CE");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbGenero;
    private org.jdesktop.swingx.JXDatePicker dpFechaNac;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocIdentidad;
    private javax.swing.JLabel txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
