/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PackDiseño;

import Clases.Paciente;
import Controladores.ControladorPaciente;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import util.Placeholders;

/**
 *
 * @author apnil
 */
public class PanelPacientes extends javax.swing.JPanel {

    /**
     * Creates new form PanelPacientes
     */
    
    public PanelPacientes() {
        initComponents();
        llenarTablaPacientes();
        mostrarTotalPacientes();
        jScrollPane2.setBorder(BorderFactory.createEmptyBorder());
        tablaPacientes.setRowHeight(30);
//        panelGradiante1.setGradientColorsAndRadius(Color.decode("#2A7B9B"), Color.decode("#EDDD53"), 40);
//        panelGradiante2.setGradientColorsAndRadius(Color.BLUE, Color.CYAN, 40);
//        panelGradiante3.setGradientColorsAndRadius(Color.decode("#D97038"), Color.decode("#89D439"), 40);
        //REDONDEO
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch(Exception ex ) {
          System.err.println( "Failed to initialize LaF" );
        }
        jPanel1.putClientProperty(FlatClientProperties.STYLE, "arc: 30");
        jPanel2.putClientProperty(FlatClientProperties.STYLE, "arc: 30");
        Placeholders.configurarPlaceholder(txtBuscar, "Ingrese el nombre o documento de identidad del paciente a buscar");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTotalPacientes = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Tabla De Pacientes Registrados");

        jScrollPane2.setBorder(null);

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellido Paterno", "Apellido Materno", "Doc Identidad", "Tipo Doc", "Fecha Nacimiento", "Edad", "Genero", "Telefono", "Correo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPacientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 930, 330));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Search.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 51, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 840, 10));

        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setText("Ingrese el nombre o documento de identidad del paciente a buscar");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 6, 840, 38));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 930, 50));

        jPanel5.setLayout(new java.awt.BorderLayout());
        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 296, 180));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalPacientes.setBackground(new java.awt.Color(0, 51, 51));
        lblTotalPacientes.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblTotalPacientes.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPacientes.setText("Total de");
        lblTotalPacientes.setOpaque(true);
        jPanel3.add(lblTotalPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 170, 160));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 930, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed
        // TODO add your handling code here:
        txtBuscar.setText("");
        txtBuscar.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtBuscarMousePressed
    private void mostrarTotalPacientes() {
    try {
        ControladorPaciente controlador = new ControladorPaciente();
        int total = controlador.contarPacientes();
        lblTotalPacientes.setText("Total de pacientes: " + total);
    } catch (Exception e) {
        lblTotalPacientes.setText("Error al contar");
        System.err.println("Error al obtener total de pacientes: " + e.getMessage());
    }
}

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void llenarTablaPacientes() {
    try {
        ControladorPaciente cp = new ControladorPaciente();
        ArrayList<Paciente> lista = cp.mostrarPacientes(); // tu nuevo método desde BD

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellido Paterno");
        modelo.addColumn("Apellido Materno");
        modelo.addColumn("Doc Identidad");
        modelo.addColumn("Tipo Doc");
        modelo.addColumn("Fecha Nacimiento") ; 
        modelo.addColumn("Edad");
        modelo.addColumn("Género");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Correo");
        modelo.addColumn("Dirección");

        for (Paciente p : lista) {
            modelo.addRow(new Object[]{
                p.getNombre(),
                p.getApellidoPaterno(),
                p.getApellidoMaterno(),
                p.getNumDoc(),
                p.getTipoDoc(),
                p.getFechaNacimiento(),
                p.verEdad(),
                p.getGenero(),
                p.getTelefono(),
                p.getCorreo(),
                p.getDireccion()
            });
        }

        tablaPacientes.setModel(modelo);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar pacientes: " + e.getMessage());
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTotalPacientes;
    private javax.swing.JTable tablaPacientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
