/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PackDiseño;

/**
 *
 * @author William
 */
public class PanelRegistrarTurnos extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrarTurnos
     */
    public PanelRegistrarTurnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSFotoCircle1 = new rojerusan.RSFotoCircle();
        rSFotoCircle2 = new rojerusan.RSFotoCircle();
        rSFotoCircle3 = new rojerusan.RSFotoCircle();
        rSFotoCircle4 = new rojerusan.RSFotoCircle();
        rSFotoCircle5 = new rojerusan.RSFotoCircle();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        dpFechaNac = new org.jdesktop.swingx.JXDatePicker();
        jLabel18 = new javax.swing.JLabel();
        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(630, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ASIGNAR TURNOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 266, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 620, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DOCTORES DISPONIBLES");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 14, 185, -1));

        rSFotoCircle1.setToolTipText("");
        rSFotoCircle1.setColorBorde(new java.awt.Color(204, 204, 204));
        rSFotoCircle1.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/Recursos/d4.jpg"))); // NOI18N
        jPanel2.add(rSFotoCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 70));

        rSFotoCircle2.setToolTipText("");
        rSFotoCircle2.setColorBorde(new java.awt.Color(204, 204, 204));
        rSFotoCircle2.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/Recursos/g.jpg"))); // NOI18N
        jPanel2.add(rSFotoCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 70));

        rSFotoCircle3.setToolTipText("");
        rSFotoCircle3.setColorBorde(new java.awt.Color(204, 204, 204));
        rSFotoCircle3.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/Recursos/d2.jpg"))); // NOI18N
        jPanel2.add(rSFotoCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 70));

        rSFotoCircle4.setToolTipText("");
        rSFotoCircle4.setColorBorde(new java.awt.Color(204, 204, 204));
        rSFotoCircle4.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/Recursos/d3.jpg"))); // NOI18N
        jPanel2.add(rSFotoCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 70));

        rSFotoCircle5.setToolTipText("");
        rSFotoCircle5.setColorBorde(new java.awt.Color(204, 204, 204));
        rSFotoCircle5.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/Recursos/d5.jpg"))); // NOI18N
        jPanel2.add(rSFotoCircle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 70));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dra. Elena Márquez");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dr. Alejandro Ríos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cirujano Cardiovascular");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Dra. Camila Ortega");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Oncóloga");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Dr. Tomás Valverde");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Neurólogo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Dr. Rodrigo Pineda");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Pediatra");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Ortopedista");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 470));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Dias:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("REGISTRAR TURNOS");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 150, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Ubicacion:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Fecha de Ingreso:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Hora de Salida:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Miercoles");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setText("Domingo");
        add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setText("Martes");
        add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setText("Lunes");
        add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox5.setText("Jueves");
        add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox6.setText("Viernes");
        add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox7.setText("Sabado");
        add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00 a.m", "18:00 a.m" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 90, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiología – Consultorios externos, Piso 2, sector B", "Medicina general / Clínica médica – Consultorios externos, Piso 1, sector A", "Pediatría – Área pediátrica, Piso 1, sector C", "Traumatología / Ortopedia – Consultorios externos, Piso 2, sector D", "Neurología – Consultorios externos, Piso 3, sector B", "Dermatología – Consultorios externos, Piso 1, sector D", "Ginecología y Obstetricia – Área maternidad, Piso 3, sector A", "Urología – Consultorios externos, Piso 2, sector E", "Gastroenterología – Consultorios externos, Piso 3, sector C", "Neumonología – Consultorios externos, Piso 2, sector F", "Endocrinología – Consultorios externos, Piso 2, sector G", "Oncología – Área oncológica, Piso 4, sector A", "Otorrinolaringología – Consultorios externos, Piso 1, sector E", "Oftalmología – Consultorios externos, Piso 1, sector F", "Psiquiatría – Área de salud mental, Piso 3, sector D", "Psicología clínica – Área de salud mental, Piso 3, sector D", "Reumatología – Consultorios externos, Piso 3, sector E", "Nefrología – Unidad renal, Piso 4, sector B", "Cirugía general – Área quirúrgica, Piso 2, quirófanos centrales", "Urgencias / Guardia médica – Planta baja, acceso principal (Guardia)", "Terapia intensiva (UCI/UTI) – Piso 4, sector de cuidados intensivos", "Radiología / Diagnóstico por imagen – Subsuelo o Planta baja", "Laboratorio clínico – Subsuelo, Laboratorio central", "Rehabilitación / Kinesiología – Planta baja o anexo de rehabilitación" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 260, 20));

        rSLabelHora1.setForeground(new java.awt.Color(0, 0, 0));
        add(rSLabelHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox3.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0:00 a.m", "12:00 a.m", "24:00 p.m" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 90, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Hora de Ingreso:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox4.setForeground(new java.awt.Color(0, 0, 0));
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 220, -1));
        add(dpFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 210, 20));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Seleccion Doctor:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Recursos/hopsital.jpg"))); // NOI18N
        add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 220, 90));

        getAccessibleContext().setAccessibleName("PanelRegistrarTurnos");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dpFechaNac;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSFotoCircle rSFotoCircle1;
    private rojerusan.RSFotoCircle rSFotoCircle2;
    private rojerusan.RSFotoCircle rSFotoCircle3;
    private rojerusan.RSFotoCircle rSFotoCircle4;
    private rojerusan.RSFotoCircle rSFotoCircle5;
    private rojeru_san.RSLabelHora rSLabelHora1;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    // End of variables declaration//GEN-END:variables
}
