/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Util.Colores;
import Util.MostrarPanelHijo;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author apnil
 */
public class FormMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuAdmin
     */
    int xMouse, yMouse;
    private Color colorTemp;
    private Colores colores = new Colores(new Color(0,125,118));
    private int[] datosAdmin;

    public FormMenuAdmin(int[] datosAdmin) {
        initComponents();
        setLocationRelativeTo(null);
        this.datosAdmin = datosAdmin;
        if (datosAdmin[1] == 1) {
            btnRegistrarDoc.setEnabled(false);
            btnRegistrarRecepcionista.setEnabled(false);
        }
        else if (datosAdmin[1] == 2) {
            btnRegistrarDoc.setEnabled(true);
            btnRegistrarRecepcionista.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        PanelMenu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionEspecialidad = new javax.swing.JButton();
        btnRegistrarDoc = new javax.swing.JButton();
        btnAsignarTurnos = new javax.swing.JButton();
        btnRegistrarRecepcionista = new javax.swing.JButton();
        PanelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        PanelHijo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSuperior.setBackground(new java.awt.Color(51, 75, 73));
        PanelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelSuperiorMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelSuperiorMouseMoved(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 75, 73));
        jButton1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jButton1.setText("x");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(51, 75, 73));
        btnMinimizar.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btnMinimizar.setText("_");
        btnMinimizar.setBorder(null);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addGap(0, 1250, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(PanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 40));

        PanelMenu.setBackground(new java.awt.Color(0, 125, 118));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 75, 73));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        PanelMenu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 110));

        btnGestionEspecialidad.setBackground(new java.awt.Color(0, 125, 118));
        btnGestionEspecialidad.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnGestionEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoRegistro.png"))); // NOI18N
        btnGestionEspecialidad.setText("Gestión de especialidades");
        btnGestionEspecialidad.setBorder(null);
        btnGestionEspecialidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEspecialidadActionPerformed(evt);
            }
        });
        PanelMenu.add(btnGestionEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 360, 80));

        btnRegistrarDoc.setBackground(new java.awt.Color(0, 125, 118));
        btnRegistrarDoc.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnRegistrarDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoDoctor.png"))); // NOI18N
        btnRegistrarDoc.setText("Registrar Doctor");
        btnRegistrarDoc.setBorder(null);
        btnRegistrarDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDocActionPerformed(evt);
            }
        });
        PanelMenu.add(btnRegistrarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 360, 80));

        btnAsignarTurnos.setBackground(new java.awt.Color(0, 125, 118));
        btnAsignarTurnos.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnAsignarTurnos.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarTurnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoCronometro.png"))); // NOI18N
        btnAsignarTurnos.setText("Gestión de turnos");
        btnAsignarTurnos.setBorder(null);
        btnAsignarTurnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsignarTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTurnosActionPerformed(evt);
            }
        });
        PanelMenu.add(btnAsignarTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 360, 80));

        btnRegistrarRecepcionista.setBackground(new java.awt.Color(0, 125, 118));
        btnRegistrarRecepcionista.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnRegistrarRecepcionista.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoDoctor.png"))); // NOI18N
        btnRegistrarRecepcionista.setText("Registrar Recepcionista");
        btnRegistrarRecepcionista.setBorder(null);
        btnRegistrarRecepcionista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRecepcionistaActionPerformed(evt);
            }
        });
        PanelMenu.add(btnRegistrarRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 360, 80));

        jPanel1.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 360, 730));

        PanelTitulo.setBackground(new java.awt.Color(150, 177, 173));

        lblTitulo.setBackground(new java.awt.Color(153, 153, 153));
        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("MENU");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(PanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 970, 60));

        PanelHijo.setLayout(new java.awt.BorderLayout());
        jPanel1.add(PanelHijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 970, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstablecerColor(JButton btn){
        colorTemp = colores.generarColorAleatorio();
        btn.setBackground(colorTemp);
        PanelTitulo.setBackground(colorTemp);
    }
    private void cambiarVistaPanel(JButton botonSeleccionado, String titulo, JPanel panelMostrar) {
        btnAsignarTurnos.setBackground(colores.colorPrincipal);
        btnGestionEspecialidad.setBackground(colores.colorPrincipal);
        btnRegistrarDoc.setBackground(colores.colorPrincipal);
        btnRegistrarRecepcionista.setBackground(colores.colorPrincipal);
        EstablecerColor(botonSeleccionado);
        lblTitulo.setText(titulo);
        MostrarPanelHijo.Mostrar(panelMostrar, PanelHijo, 970, 620);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LogRes a = new LogRes();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PanelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse , y - yMouse);
    }//GEN-LAST:event_PanelSuperiorMouseDragged

    private void PanelSuperiorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMouseMoved
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_PanelSuperiorMouseMoved

    private void btnGestionEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEspecialidadActionPerformed
        cambiarVistaPanel(btnGestionEspecialidad, "Perfil", new PanelEspecialidades());
    }//GEN-LAST:event_btnGestionEspecialidadActionPerformed

    private void btnRegistrarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDocActionPerformed
        cambiarVistaPanel(btnRegistrarDoc, "Registrar Doctor", new PanelRegistarDoctor());
    }//GEN-LAST:event_btnRegistrarDocActionPerformed

    private void btnAsignarTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTurnosActionPerformed
        cambiarVistaPanel(btnAsignarTurnos, "Turnos", new PanelRegistrarTurnos());
    }//GEN-LAST:event_btnAsignarTurnosActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnRegistrarRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRecepcionistaActionPerformed
        cambiarVistaPanel(btnRegistrarRecepcionista, "Registrar Recepcionista", new PanelRegistroRecepcionistas());
    }//GEN-LAST:event_btnRegistrarRecepcionistaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHijo;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JButton btnAsignarTurnos;
    private javax.swing.JButton btnGestionEspecialidad;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnRegistrarDoc;
    private javax.swing.JButton btnRegistrarRecepcionista;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
